// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_dev.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzuUbLCvQlrbODXvC1dCztHk86ROT1WoA',
    appId: '1:719028830605:web:7bc33a050ab87f8d703dc4',
    messagingSenderId: '719028830605',
    projectId: 'neura-dev',
    authDomain: 'neura-dev.firebaseapp.com',
    storageBucket: 'neura-dev.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB98OGOLpt5Agauuqh4EB1yFo1Q3y1IhMw',
    appId: '1:719028830605:android:a290bf8413041df3703dc4',
    messagingSenderId: '719028830605',
    projectId: 'neura-dev',
    storageBucket: 'neura-dev.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfVgkdx-dd340APuivl2coNIVUZH9N95Q',
    appId: '1:719028830605:ios:c7199543de22fe80703dc4',
    messagingSenderId: '719028830605',
    projectId: 'neura-dev',
    storageBucket: 'neura-dev.firebasestorage.app',
    iosBundleId: 'com.example.neuraChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDfVgkdx-dd340APuivl2coNIVUZH9N95Q',
    appId: '1:719028830605:ios:c7199543de22fe80703dc4',
    messagingSenderId: '719028830605',
    projectId: 'neura-dev',
    storageBucket: 'neura-dev.firebasestorage.app',
    iosBundleId: 'com.example.neuraChat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBzuUbLCvQlrbODXvC1dCztHk86ROT1WoA',
    appId: '1:719028830605:web:4d847430bef61f74703dc4',
    messagingSenderId: '719028830605',
    projectId: 'neura-dev',
    authDomain: 'neura-dev.firebaseapp.com',
    storageBucket: 'neura-dev.firebasestorage.app',
  );
}
